"""
Validate that the API registry is up-to-date.

This script checks if the API registry needs to be regenerated by comparing
the current state of API files with the last generation timestamp.

Exit codes:
- 0: Registry is up-to-date
- 1: Registry needs regeneration
- 2: Error occurred
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BACKEND_APP = ROOT / "backend" / "app"
REGISTRY_JSON_PATH = ROOT / "docs" / "api" / "API_REGISTRY.json"


def get_api_file_mtime() -> datetime:
    """Get the most recent modification time of API files."""
    api_files = []
    
    # Collect API files
    api_files.extend((BACKEND_APP / "api").rglob("*.py"))
    api_files.extend((BACKEND_APP / "modules").rglob("router.py"))
    api_files.append(BACKEND_APP / "main.py")
    
    if not api_files:
        print("Warning: No API files found")
        return datetime.min.replace(tzinfo=timezone.utc)
    
    # Find most recent modification
    most_recent = max(f.stat().st_mtime for f in api_files if f.exists())
    return datetime.fromtimestamp(most_recent, tz=timezone.utc)


def get_registry_generation_time() -> datetime | None:
    """Get the generation timestamp from the registry."""
    if not REGISTRY_JSON_PATH.exists():
        return None
    
    try:
        with open(REGISTRY_JSON_PATH) as f:
            data = json.load(f)
        
        generated_at = data.get("generated_at")
        if not generated_at:
            return None
        
        # Parse ISO format timestamp
        return datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
    
    except Exception as e:
        print(f"Error reading registry: {e}")
        return None


def main() -> int:
    """Main validation logic."""
    print("Validating API registry...")
    
    # Check if registry exists
    if not REGISTRY_JSON_PATH.exists():
        print("✗ API registry does not exist")
        print(f"  Expected: {REGISTRY_JSON_PATH}")
        print("\nRun: cd backend && python3 -m app.scripts.generate_api_registry")
        return 1
    
    # Get timestamps
    registry_time = get_registry_generation_time()
    if registry_time is None:
        print("✗ Cannot determine registry generation time")
        print("\nRun: cd backend && python3 -m app.scripts.generate_api_registry")
        return 1
    
    api_mtime = get_api_file_mtime()
    
    # Compare timestamps
    print(f"Registry generated: {registry_time.strftime('%Y-%m-%d %H:%M:%S')} UTC")
    print(f"Latest API change:  {api_mtime.strftime('%Y-%m-%d %H:%M:%S')} UTC")
    
    if api_mtime > registry_time:
        print("\n✗ API registry is out of date")
        print(f"  API files modified {(api_mtime - registry_time).total_seconds():.0f} seconds after registry generation")
        print("\nRun: cd backend && python3 -m app.scripts.generate_api_registry")
        return 1
    
    print("\n✓ API registry is up-to-date")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(2)
