"""
Disease Risk Forecast Model

Stores disease risk predictions generated by epidemiological models.

Disease Risk Models typically consider:
    - Weather conditions (temperature, humidity, leaf wetness)
    - Crop growth stage
    - Historical disease pressure
    - Inoculum presence
    
Common disease models:
    - Late Blight (Phytophthora infestans): Blitecast, SIMCAST
    - Powdery Mildew: UC Davis PM model
    - Rust diseases: Various degree-day models
"""

from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    Date,
    DateTime,
    JSON,
    ForeignKey,
)
from sqlalchemy.orm import relationship
from app.models.base import BaseModel


class DiseaseRiskForecast(BaseModel):
    """
    Represents a disease risk forecast for a specific crop at a given location.

    This model stores predictions generated by disease models, including risk levels,
    contributing factors, and recommended actions.
    
    Attributes:
        organization_id: Multi-tenant isolation (RLS)
        location_id: Reference to location for forecast
        forecast_date: Date forecast was generated
        valid_from/valid_until: Forecast validity window
        disease_name: Name of disease being forecasted
        crop_name: Target crop
        risk_level: Categorical risk (Low/Medium/High)
        risk_score: Numeric risk score (0.0-1.0)
        contributing_factors: JSON with weather/environmental factors
        recommended_actions: JSON array of management recommendations
        model_name/version: Disease model identification
    """

    __tablename__ = "disease_risk_forecasts"

    organization_id = Column(
        Integer, ForeignKey("organizations.id"), nullable=False, index=True
    )
    location_id = Column(Integer, ForeignKey("locations.id"), nullable=True, index=True)

    forecast_date = Column(Date, nullable=False, index=True)
    valid_from = Column(DateTime(timezone=True), nullable=False)
    valid_until = Column(DateTime(timezone=True), nullable=False)

    disease_name = Column(String(255), nullable=False, index=True)
    crop_name = Column(String(255), nullable=False, index=True)
    risk_level = Column(
        String(50), nullable=False, index=True
    )  # e.g., 'Low', 'Medium', 'High'
    risk_score = Column(Float, nullable=True)  # A numeric score, e.g., 0.0 to 1.0

    contributing_factors = Column(
        JSON, nullable=True
    )  # JSON object with factors like temperature, humidity
    recommended_actions = Column(
        JSON, nullable=True
    )  # JSON array of recommended actions

    model_name = Column(String(255), nullable=False)
    model_version = Column(String(50), nullable=False)

    # Relationships
    organization = relationship("Organization")
