"""Domain boundary registry for the BijMantra modular monolith."""

from app.domains.registry import (
    CANONICAL_ARCHITECTURE,
    DOMAIN_BOUNDARIES,
    DOMAIN_CODE_ROOT,
    DOMAIN_CREATION_CRITERIA,
    DOMAIN_GROWTH_POLICY,
    DOMAIN_OWNERSHIP,
    HEXAGONAL_DOMAIN_LAYERS,
    LEGACY_ARCHITECTURE_ALIASES,
    LEGACY_DOMAIN_ALIASES,
    LEGACY_LOKA_ALIASES,
    LOKA_BOUNDARIES,
    LOKA_DOMAIN_OWNERSHIP,
    TRANSITIONAL_SURFACES,
    DomainBoundary,
    LokaBoundary,
    resolve_domain_for_capability,
    resolve_domain_name,
    resolve_loka_for_domain,
    resolve_loka_name,
)

__all__ = [
    "CANONICAL_ARCHITECTURE",
    "DOMAIN_BOUNDARIES",
    "DOMAIN_CODE_ROOT",
    "DOMAIN_CREATION_CRITERIA",
    "DOMAIN_GROWTH_POLICY",
    "DOMAIN_OWNERSHIP",
    "HEXAGONAL_DOMAIN_LAYERS",
    "LEGACY_ARCHITECTURE_ALIASES",
    "LEGACY_DOMAIN_ALIASES",
    "LEGACY_LOKA_ALIASES",
    "LOKA_BOUNDARIES",
    "LOKA_DOMAIN_OWNERSHIP",
    "TRANSITIONAL_SURFACES",
    "DomainBoundary",
    "LokaBoundary",
    "resolve_domain_for_capability",
    "resolve_domain_name",
    "resolve_loka_for_domain",
    "resolve_loka_name",
]
