from app.scripts.generate_api_docs import build_markdown


def test_build_markdown_contains_sections():
    fake_spec = {
        'routes': [
            {'method': 'GET', 'path': '/health', 'summary': 'Health check', 'source': 'backend/app/main.py'}
        ],
        'models': ['HealthResponse'],
    }

    output = build_markdown(fake_spec)
    assert '# AUTOGENERATED API SPEC' in output
    assert '## Routes' in output
    assert '`/health`' in output
    assert '`HealthResponse`' in output
