from dataclasses import dataclass
from typing import Any


PROPOSAL_META_FIELDS = {
    "organization_id",
    "user_id",
    "title",
    "description",
    "rationale",
    "confidence",
}


@dataclass(frozen=True)
class ProposalHandlerSharedContext:
    action_type_enum: Any
    get_proposal_service: Any


def _extract_target_data(params: dict[str, Any]) -> dict[str, Any]:
    return {
        key: value
        for key, value in params.items()
        if key not in PROPOSAL_META_FIELDS
    }


async def handle_proposal(
    executor: Any,
    function_name: str,
    params: dict[str, Any],
    *,
    shared: ProposalHandlerSharedContext,
    logger: Any,
) -> dict[str, Any]:
    """Handle propose_* functions via a dedicated sibling module."""
    org_id = params.get("organization_id", 1)
    user_id = params.get("user_id")
    title = params.get("title", f"Proposal for {function_name}")
    description = params.get("description", "Generated by AI Scribe")
    rationale = params.get("rationale", "Based on user request and data analysis")
    confidence = params.get("confidence", 70)

    action_type = None
    target_data: dict[str, Any] = {}

    if function_name == "propose_create_trial":
        action_type = shared.action_type_enum.CREATE_TRIAL
        target_data = _extract_target_data(params)
    elif function_name == "propose_create_cross":
        action_type = shared.action_type_enum.CREATE_CROSS
        target_data = _extract_target_data(params)
    elif function_name == "propose_record_observation":
        action_type = shared.action_type_enum.RECORD_OBSERVATION
        target_data = _extract_target_data(params)
    else:
        return {
            "success": False,
            "error": f"Unknown proposal type: {function_name}",
            "message": "This action cannot be proposed.",
        }

    try:
        proposal_service = shared.get_proposal_service()
        proposal = await proposal_service.create_proposal(
            db=executor.db,
            organization_id=org_id,
            title=title,
            description=description,
            action_type=action_type,
            target_data=target_data,
            ai_rationale=rationale,
            confidence_score=confidence,
            user_id=user_id,
        )

        return {
            "success": True,
            "function": function_name,
            "result_type": "proposal_created",
            "data": {
                "proposal_id": proposal.id,
                "status": proposal.status,
                "title": proposal.title,
                "message": f"Proposal created successfully (ID: {proposal.id}). Pending review.",
            },
            "demo": False,
        }
    except Exception as error:
        logger.error("Proposal creation failed: %s", error)
        return {
            "success": False,
            "error": str(error),
            "message": "Failed to create proposal",
        }