import importlib.util
import os
import uuid
from pathlib import Path

import alembic.op as alembic_op
import pytest
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, exc, text


pytestmark = [pytest.mark.integration, pytest.mark.postgres_integration]

POSTGRES_DSN_ENV = "BIJMANTRA_TEST_POSTGRES_DSN"


def _load_migration_module():
    module_path = (
        Path(__file__).resolve().parents[2]
        / "alembic/versions/20260313_0200_adr006_devguru_veena_ownership_rls.py"
    )
    spec = importlib.util.spec_from_file_location("adr006_veena_rls_migration", module_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _set_search_path(connection, schema_name: str) -> None:
    connection.execute(text(f'SET search_path TO "{schema_name}", public'))


def _set_rls_context(connection, organization_id: int, user_id: int) -> None:
    connection.execute(
        text("SELECT set_config('app.current_organization_id', :value, true)"),
        {"value": str(organization_id)},
    )
    connection.execute(
        text("SELECT set_config('app.current_user_id', :value, true)"),
        {"value": str(user_id)},
    )

    current_org = connection.execute(
        text("SELECT current_setting('app.current_organization_id', true)")
    ).scalar_one()
    current_user = connection.execute(
        text("SELECT current_setting('app.current_user_id', true)")
    ).scalar_one()

    assert current_org == str(organization_id)
    assert current_user == str(user_id)


def _create_pre_upgrade_schema(connection) -> None:
    connection.execute(
        text(
            """
            CREATE TABLE organizations (
                id INTEGER PRIMARY KEY,
                name TEXT NOT NULL
            );

            CREATE TABLE users (
                id INTEGER PRIMARY KEY,
                organization_id INTEGER NOT NULL REFERENCES organizations(id),
                email TEXT NOT NULL,
                hashed_password TEXT NOT NULL
            );

            CREATE TABLE programs (
                id INTEGER PRIMARY KEY,
                organization_id INTEGER NOT NULL REFERENCES organizations(id),
                program_name TEXT NOT NULL,
                is_research_project BOOLEAN NOT NULL DEFAULT FALSE,
                research_context JSONB NULL
            );

            CREATE TABLE research_projects (
                id VARCHAR(50) PRIMARY KEY,
                user_id INTEGER REFERENCES users(id),
                program_id INTEGER REFERENCES programs(id),
                title TEXT NOT NULL,
                student_name TEXT NOT NULL,
                start_date DATE NOT NULL,
                expected_end_date DATE NOT NULL,
                current_phase VARCHAR(50),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE research_papers (
                id VARCHAR(50) PRIMARY KEY,
                project_id VARCHAR(50) NOT NULL REFERENCES research_projects(id),
                title TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE paper_experiment_links (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                paper_id VARCHAR(50) NOT NULL REFERENCES research_papers(id),
                trial_id INTEGER,
                study_id INTEGER,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE thesis_chapters (
                id VARCHAR(50) PRIMARY KEY,
                project_id VARCHAR(50) NOT NULL REFERENCES research_projects(id),
                title TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE writing_sessions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chapter_id VARCHAR(50) NOT NULL REFERENCES thesis_chapters(id),
                session_date DATE NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE committee_members (
                id VARCHAR(50) PRIMARY KEY,
                project_id VARCHAR(50) NOT NULL REFERENCES research_projects(id),
                name TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE committee_meetings (
                id VARCHAR(50) PRIMARY KEY,
                project_id VARCHAR(50) NOT NULL REFERENCES research_projects(id),
                title TEXT NOT NULL,
                scheduled_date TIMESTAMPTZ NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE feedback_items (
                id VARCHAR(50) PRIMARY KEY,
                project_id VARCHAR(50) NOT NULL REFERENCES research_projects(id),
                chapter_id VARCHAR(50) REFERENCES thesis_chapters(id),
                meeting_id VARCHAR(50) REFERENCES committee_meetings(id),
                from_member_id VARCHAR(50) REFERENCES committee_members(id),
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE veena_memories_v2 (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                query TEXT NOT NULL,
                response TEXT NOT NULL,
                context_tags JSONB NOT NULL,
                embedding JSONB,
                pinned BOOLEAN NOT NULL DEFAULT FALSE,
                ttl_days INTEGER,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE veena_user_contexts_v2 (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL UNIQUE,
                preferences JSONB NOT NULL,
                expertise_level VARCHAR(64) NOT NULL DEFAULT 'manager',
                active_project VARCHAR(255),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE veena_audit_logs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                session_id VARCHAR(128),
                prompt TEXT NOT NULL,
                generated_draft TEXT NOT NULL,
                flagged_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE veena_reasoning_traces_v2 (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id VARCHAR(128) NOT NULL,
                step_id VARCHAR(128) NOT NULL,
                thought TEXT NOT NULL,
                tool_used VARCHAR(128),
                outcome TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            """
        )
    )


def _assert_rls_violation(error: exc.DBAPIError) -> None:
    message = str(error).lower()
    assert "row-level security" in message or "violates row-level security policy" in message


def _seed_pre_upgrade_data(connection) -> None:
    connection.execute(
        text(
            """
            INSERT INTO organizations (id, name)
            VALUES (1, 'Org One'), (2, 'Org Two');

            INSERT INTO users (id, organization_id, email, hashed_password)
            VALUES
                (10, 1, 'owner@example.com', 'hashed'),
                (11, 1, 'peer@example.com', 'hashed'),
                (20, 2, 'other-org@example.com', 'hashed');

            INSERT INTO programs (id, organization_id, program_name, is_research_project, research_context)
            VALUES
                (100, 1, 'Program One', TRUE, '{"stage": "phd"}'::jsonb),
                (200, 2, 'Program Two', TRUE, '{"stage": "phd"}'::jsonb);

            INSERT INTO research_projects (id, user_id, program_id, title, student_name, start_date, expected_end_date, current_phase)
            VALUES
                ('proj-owner', 10, 100, 'Owner project', 'Owner Student', DATE '2025-01-01', DATE '2027-01-01', 'writing'),
                ('proj-other', 20, 200, 'Other project', 'Other Student', DATE '2025-01-01', DATE '2027-01-01', 'writing');

            INSERT INTO research_papers (id, project_id, title)
            VALUES
                ('paper-owner', 'proj-owner', 'Owner paper'),
                ('paper-other', 'proj-other', 'Other paper');

            INSERT INTO paper_experiment_links (paper_id, trial_id, study_id)
            VALUES
                ('paper-owner', NULL, NULL),
                ('paper-other', NULL, NULL);

            INSERT INTO thesis_chapters (id, project_id, title)
            VALUES
                ('chapter-owner', 'proj-owner', 'Owner chapter'),
                ('chapter-other', 'proj-other', 'Other chapter');

            INSERT INTO writing_sessions (chapter_id, session_date)
            VALUES
                ('chapter-owner', DATE '2026-03-10'),
                ('chapter-other', DATE '2026-03-10');

            INSERT INTO committee_members (id, project_id, name)
            VALUES
                ('member-owner', 'proj-owner', 'Owner Mentor'),
                ('member-other', 'proj-other', 'Other Mentor');

            INSERT INTO committee_meetings (id, project_id, title, scheduled_date)
            VALUES
                ('meeting-owner', 'proj-owner', 'Owner meeting', TIMESTAMPTZ '2026-03-10 10:00:00+00'),
                ('meeting-other', 'proj-other', 'Other meeting', TIMESTAMPTZ '2026-03-10 10:00:00+00');

            INSERT INTO feedback_items (id, project_id, chapter_id, meeting_id, from_member_id, content)
            VALUES
                ('feedback-owner', 'proj-owner', 'chapter-owner', 'meeting-owner', 'member-owner', 'Owner feedback'),
                ('feedback-other', 'proj-other', 'chapter-other', 'meeting-other', 'member-other', 'Other feedback');

            INSERT INTO veena_memories_v2 (user_id, query, response, context_tags, embedding, pinned, ttl_days)
            VALUES
                (10, 'owner query', 'owner response', '["veena", "owner"]'::jsonb, '[0.1, 0.2]'::jsonb, FALSE, NULL),
                (20, 'other query', 'other response', '["veena", "other"]'::jsonb, '[0.3, 0.4]'::jsonb, FALSE, NULL);

            INSERT INTO veena_user_contexts_v2 (user_id, preferences, expertise_level, active_project)
            VALUES
                (10, '{"tone": "formal"}'::jsonb, 'manager', 'Owner project'),
                (20, '{"tone": "formal"}'::jsonb, 'manager', 'Other project');

            INSERT INTO veena_audit_logs (user_id, session_id, prompt, generated_draft, flagged_sensitive)
            VALUES
                (10, 'session-owner', 'prompt a', 'draft a', FALSE),
                (20, 'session-other-org', 'prompt b', 'draft b', FALSE);

            INSERT INTO veena_reasoning_traces_v2 (session_id, step_id, thought, tool_used, outcome)
            VALUES
                ('session-owner', 'analyze', 'Analyze user intent', 'intent-parser', 'intent-captured'),
                ('session-other-org', 'analyze', 'Analyze other org intent', 'intent-parser', 'intent-captured');
            """
        )
    )


def _run_migration_upgrade(connection, migration) -> None:
    context = MigrationContext.configure(connection)
    operations = Operations(context)
    previous_proxy = getattr(alembic_op, "_proxy", None)
    alembic_op._proxy = operations
    try:
        migration.upgrade()
    finally:
        if previous_proxy is None:
            if hasattr(alembic_op, "_proxy"):
                del alembic_op._proxy
        else:
            alembic_op._proxy = previous_proxy


@pytest.fixture(scope="module")
def postgres_engine():
    dsn = os.getenv(POSTGRES_DSN_ENV)
    if not dsn:
        pytest.skip(f"set {POSTGRES_DSN_ENV} to run Postgres RLS integration tests")

    engine = create_engine(dsn, future=True)
    with engine.connect() as connection:
        role = connection.execute(
            text(
                """
                SELECT rolsuper, rolbypassrls
                FROM pg_roles
                WHERE rolname = current_user
                """
            )
        ).one()
        if role.rolsuper or role.rolbypassrls:
            pytest.skip("Postgres RLS proof requires a non-superuser role without BYPASSRLS")

    try:
        yield engine
    finally:
        engine.dispose()


@pytest.fixture(scope="module")
def veena_rls_schema(postgres_engine):
    schema_name = f"adr006_veena_rls_{uuid.uuid4().hex[:8]}"
    migration = _load_migration_module()

    with postgres_engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{schema_name}"'))
        _set_search_path(connection, schema_name)
        _create_pre_upgrade_schema(connection)
        _seed_pre_upgrade_data(connection)
        _run_migration_upgrade(connection, migration)

    try:
        yield schema_name
    finally:
        with postgres_engine.begin() as connection:
            connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema_name}" CASCADE'))


def test_upgrade_backfills_organization_ids_and_enables_veena_policies(postgres_engine, veena_rls_schema):
    tables = [
        "research_projects",
        "paper_experiment_links",
        "writing_sessions",
        "committee_members",
        "committee_meetings",
        "feedback_items",
        "veena_memories_v2",
        "veena_user_contexts_v2",
        "veena_audit_logs",
        "veena_reasoning_traces_v2",
    ]

    with postgres_engine.begin() as connection:
        _set_search_path(connection, veena_rls_schema)
        _set_rls_context(connection, organization_id=0, user_id=10)

        null_counts = {
            table_name: connection.execute(
                text(f"SELECT COUNT(*) FROM {table_name} WHERE organization_id IS NULL")
            ).scalar_one()
            for table_name in tables
        }

        owner_trace_org = connection.execute(
            text(
                "SELECT organization_id FROM veena_reasoning_traces_v2 WHERE session_id = 'session-owner'"
            )
        ).scalar_one()
        owner_audit_org = connection.execute(
            text("SELECT organization_id FROM veena_audit_logs WHERE session_id = 'session-owner'")
        ).scalar_one()
        owner_memory_org = connection.execute(
            text("SELECT organization_id FROM veena_memories_v2 WHERE user_id = 10")
        ).scalar_one()
        owner_project_org = connection.execute(
            text("SELECT organization_id FROM research_projects WHERE id = 'proj-owner'")
        ).scalar_one()
        force_rls = connection.execute(
            text(
                """
                SELECT relrowsecurity, relforcerowsecurity
                FROM pg_class
                WHERE oid = to_regclass(:table_name)
                """
            ),
            {"table_name": f'{veena_rls_schema}.veena_reasoning_traces_v2'},
        ).one()

    assert all(count == 0 for count in null_counts.values())
    assert owner_trace_org == 1
    assert owner_audit_org == 1
    assert owner_memory_org == 1
    assert owner_project_org == 1
    assert force_rls.relrowsecurity is True
    assert force_rls.relforcerowsecurity is True


def test_reasoning_trace_reads_are_scoped_by_user_and_org(postgres_engine, veena_rls_schema):
    with postgres_engine.begin() as connection:
        _set_search_path(connection, veena_rls_schema)
        _set_rls_context(connection, organization_id=1, user_id=10)

        owner_trace_count = connection.execute(
            text("SELECT COUNT(*) FROM veena_reasoning_traces_v2 WHERE session_id = 'session-owner'")
        ).scalar_one()
        owner_audit_count = connection.execute(
            text("SELECT COUNT(*) FROM veena_audit_logs WHERE session_id = 'session-owner'")
        ).scalar_one()

    assert owner_trace_count == 1
    assert owner_audit_count == 1

    with postgres_engine.begin() as connection:
        _set_search_path(connection, veena_rls_schema)
        _set_rls_context(connection, organization_id=1, user_id=11)

        peer_trace_count = connection.execute(
            text("SELECT COUNT(*) FROM veena_reasoning_traces_v2 WHERE session_id = 'session-owner'")
        ).scalar_one()
        peer_audit_count = connection.execute(
            text("SELECT COUNT(*) FROM veena_audit_logs WHERE session_id = 'session-owner'")
        ).scalar_one()

    assert peer_trace_count == 0
    assert peer_audit_count == 0

    with postgres_engine.begin() as connection:
        _set_search_path(connection, veena_rls_schema)
        _set_rls_context(connection, organization_id=2, user_id=20)

        cross_org_trace_count = connection.execute(
            text("SELECT COUNT(*) FROM veena_reasoning_traces_v2 WHERE session_id = 'session-owner'")
        ).scalar_one()
        own_org_trace_count = connection.execute(
            text("SELECT COUNT(*) FROM veena_reasoning_traces_v2 WHERE session_id = 'session-other-org'")
        ).scalar_one()

    assert cross_org_trace_count == 0
    assert own_org_trace_count == 1


def test_reasoning_trace_reads_fail_closed_without_context(postgres_engine, veena_rls_schema):
    with postgres_engine.begin() as connection:
        _set_search_path(connection, veena_rls_schema)

        trace_count = connection.execute(text("SELECT COUNT(*) FROM veena_reasoning_traces_v2")).scalar_one()
        audit_count = connection.execute(text("SELECT COUNT(*) FROM veena_audit_logs")).scalar_one()

    assert trace_count == 0
    assert audit_count == 0


def test_reasoning_trace_insert_requires_matching_audit_log(postgres_engine, veena_rls_schema):
    with postgres_engine.begin() as connection:
        _set_search_path(connection, veena_rls_schema)
        _set_rls_context(connection, organization_id=1, user_id=10)

        connection.execute(
            text(
                """
                INSERT INTO veena_reasoning_traces_v2 (organization_id, session_id, step_id, thought, tool_used, outcome)
                VALUES (1, 'session-owner', 'retrieve', 'Fetch relevant memory', 'pgvector', 'context_hits=1')
                """
            )
        )

        owner_insert_count = connection.execute(
            text("SELECT COUNT(*) FROM veena_reasoning_traces_v2 WHERE session_id = 'session-owner'")
        ).scalar_one()

    assert owner_insert_count == 2

    with pytest.raises(exc.DBAPIError) as peer_insert_error:
        with postgres_engine.begin() as connection:
            _set_search_path(connection, veena_rls_schema)
            _set_rls_context(connection, organization_id=1, user_id=11)
            connection.execute(
                text(
                    """
                    INSERT INTO veena_reasoning_traces_v2 (organization_id, session_id, step_id, thought, tool_used, outcome)
                    VALUES (1, 'session-owner', 'peer-write', 'Peer write attempt', 'pgvector', 'denied')
                    """
                )
            )
    _assert_rls_violation(peer_insert_error.value)

    with pytest.raises(exc.DBAPIError) as no_context_insert_error:
        with postgres_engine.begin() as connection:
            _set_search_path(connection, veena_rls_schema)
            connection.execute(
                text(
                    """
                    INSERT INTO veena_reasoning_traces_v2 (organization_id, session_id, step_id, thought, tool_used, outcome)
                    VALUES (1, 'session-owner', 'no-context-write', 'No context write attempt', 'pgvector', 'denied')
                    """
                )
            )
    _assert_rls_violation(no_context_insert_error.value)


def test_reasoning_trace_update_requires_matching_audit_log(postgres_engine, veena_rls_schema):
    with pytest.raises(exc.DBAPIError) as update_error:
        with postgres_engine.begin() as connection:
            _set_search_path(connection, veena_rls_schema)
            _set_rls_context(connection, organization_id=1, user_id=10)
            connection.execute(
                text(
                    """
                    UPDATE veena_reasoning_traces_v2
                    SET session_id = 'session-without-audit'
                    WHERE session_id = 'session-owner' AND step_id = 'analyze'
                    """
                )
            )
    _assert_rls_violation(update_error.value)