import { SynthesisResult } from '@/types/devguru'

interface SynthesisTabProps {
  synthesis: SynthesisResult | undefined
  isLoading: boolean
  onRefresh: () => void
}

export function SynthesisTab({ synthesis, isLoading, onRefresh }: SynthesisTabProps) {
  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin w-8 h-8 border-2 border-purple-500 border-t-transparent rounded-full mx-auto mb-2" />
          <p className="text-sm text-gray-500">Generating synthesis...</p>
        </div>
      </div>
    )
  }

  if (!synthesis) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="text-center max-w-md">
          <span className="text-4xl mb-4 block">🔬</span>
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Research Synthesis</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Select a project to generate AI synthesis of your research progress.
          </p>
        </div>
      </div>
    )
  }

  const { context, synthesis: synthContent, message } = synthesis

  return (
    <div className="flex-1 overflow-y-auto p-4">
      {/* Summary Stats */}
      <div className="grid grid-cols-3 gap-3 mb-4">
        <div className="bg-purple-50 dark:bg-purple-900/20 rounded-lg p-3 text-center">
          <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{context.summary.total_experiments}</p>
          <p className="text-xs text-purple-700 dark:text-purple-300">Experiments</p>
        </div>
        <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-3 text-center">
          <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">{context.summary.active_experiments}</p>
          <p className="text-xs text-blue-700 dark:text-blue-300">Active</p>
        </div>
        <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-3 text-center">
          <p className="text-2xl font-bold text-green-600 dark:text-green-400">{context.summary.total_studies}</p>
          <p className="text-xs text-green-700 dark:text-green-300">Studies</p>
        </div>
      </div>

      {/* Synthesis Content */}
      {synthContent ? (
        <div className="bg-gray-50 dark:bg-gray-700/50 rounded-lg p-4">
          <div className="flex items-center justify-between mb-3">
            <h4 className="text-sm font-semibold text-gray-900 dark:text-white">AI Synthesis</h4>
            <button
              onClick={onRefresh}
              className="text-xs text-purple-600 dark:text-purple-400 hover:underline"
            >
              Refresh
            </button>
          </div>
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap">{synthContent.content}</p>
          </div>
          <p className="text-[10px] text-gray-400 mt-3">
            Generated by {synthContent.provider} ({synthContent.model})
          </p>
        </div>
      ) : (
        <div className="bg-yellow-50 dark:bg-yellow-900/20 rounded-lg p-4">
          <p className="text-sm text-yellow-700 dark:text-yellow-300">{message || 'No synthesis available'}</p>
        </div>
      )}

      {/* Objectives */}
      {context.project.objectives.length > 0 && (
        <div className="mt-4">
          <h4 className="text-sm font-semibold text-gray-900 dark:text-white mb-2">Research Objectives</h4>
          <ul className="space-y-1">
            {context.project.objectives.map((obj, idx) => (
              <li key={idx} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-300">
                <span className="text-purple-500">•</span>
                {obj}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}
