"""Add Mars research tables: environment profiles, trials, and metrics

Revision ID: 5fc61144136f
Revises: 4097beta
Create Date: 2026-01-31 05:15:27.072372+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '5fc61144136f'
down_revision = '4097beta'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS marsfailuremode CASCADE")
    
    # Mars Environment Profiles
    op.create_table('mars_environment_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('pressure_kpa', sa.Float(), nullable=False),
    sa.Column('co2_ppm', sa.Float(), nullable=False),
    sa.Column('o2_ppm', sa.Float(), nullable=False),
    sa.Column('radiation_msv', sa.Float(), nullable=False),
    sa.Column('gravity_factor', sa.Float(), nullable=False),
    sa.Column('photoperiod_hours', sa.Float(), nullable=False),
    sa.Column('temperature_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('humidity_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mars_environment_profiles_organization_id'), 'mars_environment_profiles', ['organization_id'], unique=False)

    # Mars Trials
    op.create_table('mars_trials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('environment_profile_id', sa.UUID(), nullable=False),
    sa.Column('germplasm_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('survival_score', sa.Float(), nullable=False),
    sa.Column('biomass_yield', sa.Float(), nullable=False),
    sa.Column('failure_mode', sa.Enum('ATMOSPHERIC_COLLAPSE', 'RADIATION_DAMAGE', 'WATER_STARVATION', 'NUTRIENT_LOCKOUT', 'ENERGY_DEFICIT', 'PHYSIOLOGICAL_LIMIT', 'UNKNOWN', name='marsfailuremode'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['environment_profile_id'], ['mars_environment_profiles.id'], ),
    sa.ForeignKeyConstraint(['germplasm_id'], ['germplasm.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mars_trials_organization_id'), 'mars_trials', ['organization_id'], unique=False)

    # Mars Metrics
    op.create_table('mars_closed_loop_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=False),
    sa.Column('water_recycling_pct', sa.Float(), nullable=False),
    sa.Column('nutrient_loss_pct', sa.Float(), nullable=False),
    sa.Column('energy_input_kwh', sa.Float(), nullable=False),
    sa.Column('oxygen_output', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['mars_trials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mars_closed_loop_metrics')
    op.drop_index(op.f('ix_mars_trials_organization_id'), table_name='mars_trials')
    op.drop_table('mars_trials')
    op.drop_index(op.f('ix_mars_environment_profiles_organization_id'), table_name='mars_environment_profiles')
    op.drop_table('mars_environment_profiles')
    # ### end Alembic commands ###
