"""Add Veena Cognitive Core tables

Revision ID: aad263aa4f43
Revises: 044
Create Date: 2026-02-02 09:57:23.917728+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '045'
down_revision = '044'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veena_memories',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.Enum('EPISODIC', 'SEMANTIC', 'PROCEDURAL', name='memorytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.Enum('EXPERIMENT', 'FIELD', 'TRIAL', 'GERMPLASM', 'CROSS', 'OBSERVATION', 'USER', 'GENERAL', name='entitytype'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_veena_memories_entity', 'veena_memories', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_veena_memories_org_user', 'veena_memories', ['organization_id', 'user_id'], unique=False)
    op.create_index('idx_veena_memories_type', 'veena_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_veena_memories_id'), 'veena_memories', ['id'], unique=False)
    op.create_index(op.f('ix_veena_memories_organization_id'), 'veena_memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_veena_memories_user_id'), 'veena_memories', ['user_id'], unique=False)
    op.create_table('veena_reasoning_traces',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('CONCEPT', 'HYPOTHESIS', 'DEDUCTION', 'CONCLUSION', name='reasoningstage'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('evidence_sources', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('entity_type', sa.Enum('EXPERIMENT', 'FIELD', 'TRIAL', 'GERMPLASM', 'CROSS', 'OBSERVATION', 'USER', 'GENERAL', name='entitytype'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['veena_reasoning_traces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reasoning_traces_org', 'veena_reasoning_traces', ['organization_id'], unique=False)
    op.create_index('idx_reasoning_traces_parent', 'veena_reasoning_traces', ['parent_id'], unique=False)
    op.create_index('idx_reasoning_traces_session', 'veena_reasoning_traces', ['session_id'], unique=False)
    op.create_index(op.f('ix_veena_reasoning_traces_id'), 'veena_reasoning_traces', ['id'], unique=False)
    op.create_index(op.f('ix_veena_reasoning_traces_organization_id'), 'veena_reasoning_traces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_veena_reasoning_traces_session_id'), 'veena_reasoning_traces', ['session_id'], unique=False)
    op.create_table('veena_user_contexts',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('response_verbosity', sa.String(length=20), nullable=False),
    sa.Column('expertise_areas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('focus_programs', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frequently_asked_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_contexts_org_user', 'veena_user_contexts', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_veena_user_contexts_id'), 'veena_user_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_veena_user_contexts_organization_id'), 'veena_user_contexts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_veena_user_contexts_user_id'), 'veena_user_contexts', ['user_id'], unique=True)
    # op.drop_table('spatial_ref_sys')
    # op.alter_column('organizations', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('organizations', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('users', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('users', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_veena_user_contexts_user_id'), table_name='veena_user_contexts')
    op.drop_index(op.f('ix_veena_user_contexts_organization_id'), table_name='veena_user_contexts')
    op.drop_index(op.f('ix_veena_user_contexts_id'), table_name='veena_user_contexts')
    op.drop_index('idx_user_contexts_org_user', table_name='veena_user_contexts')
    op.drop_table('veena_user_contexts')
    op.drop_index(op.f('ix_veena_reasoning_traces_session_id'), table_name='veena_reasoning_traces')
    op.drop_index(op.f('ix_veena_reasoning_traces_organization_id'), table_name='veena_reasoning_traces')
    op.drop_index(op.f('ix_veena_reasoning_traces_id'), table_name='veena_reasoning_traces')
    op.drop_index('idx_reasoning_traces_session', table_name='veena_reasoning_traces')
    op.drop_index('idx_reasoning_traces_parent', table_name='veena_reasoning_traces')
    op.drop_index('idx_reasoning_traces_org', table_name='veena_reasoning_traces')
    op.drop_table('veena_reasoning_traces')
    op.drop_index(op.f('ix_veena_memories_user_id'), table_name='veena_memories')
    op.drop_index(op.f('ix_veena_memories_organization_id'), table_name='veena_memories')
    op.drop_index(op.f('ix_veena_memories_id'), table_name='veena_memories')
    op.drop_index('idx_veena_memories_type', table_name='veena_memories')
    op.drop_index('idx_veena_memories_org_user', table_name='veena_memories')
    op.drop_index('idx_veena_memories_entity', table_name='veena_memories')
    op.drop_table('veena_memories')
    # ### end Alembic commands ###
