"""Add Bio-Analytics Models

Revision ID: 9db32f536d6b
Revises: 046
Create Date: 2026-02-04 05:58:53.419652+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.core.rls import generate_rls_policy_sql

# revision identifiers, used by Alembic.
revision = '9db32f536d6b'
down_revision = '046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_gs_models',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('trait_name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_population_size', sa.Integer(), nullable=True),
    sa.Column('marker_count', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('heritability', sa.Float(), nullable=True),
    sa.Column('genetic_variance', sa.Float(), nullable=True),
    sa.Column('error_variance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_gs_models_id'), 'bio_gs_models', ['id'], unique=False)
    op.create_index(op.f('ix_bio_gs_models_organization_id'), 'bio_gs_models', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bio_gs_models_trait_name'), 'bio_gs_models', ['trait_name'], unique=False)
    op.create_table('bio_gwas_runs',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(length=255), nullable=False),
    sa.Column('trait_name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('marker_count', sa.Integer(), nullable=True),
    sa.Column('significance_threshold', sa.Float(), nullable=True),
    sa.Column('significant_marker_count', sa.Integer(), nullable=True),
    sa.Column('manhattan_plot_data', sa.JSON(), nullable=True),
    sa.Column('qq_plot_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_gwas_runs_id'), 'bio_gwas_runs', ['id'], unique=False)
    op.create_index(op.f('ix_bio_gwas_runs_organization_id'), 'bio_gwas_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bio_gwas_runs_trait_name'), 'bio_gwas_runs', ['trait_name'], unique=False)
    op.create_table('bio_gebv_predictions',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('germplasm_id', sa.String(length=255), nullable=False),
    sa.Column('gebv', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('predicted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['bio_gs_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_gebv_predictions_germplasm_id'), 'bio_gebv_predictions', ['germplasm_id'], unique=False)
    op.create_index(op.f('ix_bio_gebv_predictions_id'), 'bio_gebv_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_bio_gebv_predictions_model_id'), 'bio_gebv_predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_bio_gebv_predictions_organization_id'), 'bio_gebv_predictions', ['organization_id'], unique=False)
    op.create_table('bio_gwas_results',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('marker_name', sa.String(length=255), nullable=False),
    sa.Column('chromosome', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('neg_log10_p', sa.Float(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('standard_error', sa.Float(), nullable=True),
    sa.Column('maf', sa.Float(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['bio_gwas_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_gwas_results_id'), 'bio_gwas_results', ['id'], unique=False)
    op.create_index(op.f('ix_bio_gwas_results_marker_name'), 'bio_gwas_results', ['marker_name'], unique=False)
    op.create_index(op.f('ix_bio_gwas_results_organization_id'), 'bio_gwas_results', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bio_gwas_results_run_id'), 'bio_gwas_results', ['run_id'], unique=False)
    op.create_table('bio_marker_effects',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('marker_name', sa.String(length=255), nullable=False),
    sa.Column('chromosome', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('effect', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['bio_gs_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_marker_effects_id'), 'bio_marker_effects', ['id'], unique=False)
    op.create_index(op.f('ix_bio_marker_effects_marker_name'), 'bio_marker_effects', ['marker_name'], unique=False)
    op.create_index(op.f('ix_bio_marker_effects_model_id'), 'bio_marker_effects', ['model_id'], unique=False)
    op.create_index(op.f('ix_bio_marker_effects_organization_id'), 'bio_marker_effects', ['organization_id'], unique=False)
    # op.drop_table('spatial_ref_sys') # Safety Check: Do not drop PostGIS table
    # op.alter_column('organizations', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('organizations', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('users', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('users', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # ### end Alembic commands ###

    # Apply RLS Policies
    op.execute(generate_rls_policy_sql('bio_gs_models'))
    op.execute(generate_rls_policy_sql('bio_gwas_runs'))
    op.execute(generate_rls_policy_sql('bio_gebv_predictions'))
    op.execute(generate_rls_policy_sql('bio_gwas_results'))
    op.execute(generate_rls_policy_sql('bio_marker_effects'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_index(op.f('ix_bio_marker_effects_organization_id'), table_name='bio_marker_effects')
    op.drop_index(op.f('ix_bio_marker_effects_model_id'), table_name='bio_marker_effects')
    op.drop_index(op.f('ix_bio_marker_effects_marker_name'), table_name='bio_marker_effects')
    op.drop_index(op.f('ix_bio_marker_effects_id'), table_name='bio_marker_effects')
    op.drop_table('bio_marker_effects')
    op.drop_index(op.f('ix_bio_gwas_results_run_id'), table_name='bio_gwas_results')
    op.drop_index(op.f('ix_bio_gwas_results_organization_id'), table_name='bio_gwas_results')
    op.drop_index(op.f('ix_bio_gwas_results_marker_name'), table_name='bio_gwas_results')
    op.drop_index(op.f('ix_bio_gwas_results_id'), table_name='bio_gwas_results')
    op.drop_table('bio_gwas_results')
    op.drop_index(op.f('ix_bio_gebv_predictions_organization_id'), table_name='bio_gebv_predictions')
    op.drop_index(op.f('ix_bio_gebv_predictions_model_id'), table_name='bio_gebv_predictions')
    op.drop_index(op.f('ix_bio_gebv_predictions_id'), table_name='bio_gebv_predictions')
    op.drop_index(op.f('ix_bio_gebv_predictions_germplasm_id'), table_name='bio_gebv_predictions')
    op.drop_table('bio_gebv_predictions')
    op.drop_index(op.f('ix_bio_gwas_runs_trait_name'), table_name='bio_gwas_runs')
    op.drop_index(op.f('ix_bio_gwas_runs_organization_id'), table_name='bio_gwas_runs')
    op.drop_index(op.f('ix_bio_gwas_runs_id'), table_name='bio_gwas_runs')
    op.drop_table('bio_gwas_runs')
    op.drop_index(op.f('ix_bio_gs_models_trait_name'), table_name='bio_gs_models')
    op.drop_index(op.f('ix_bio_gs_models_organization_id'), table_name='bio_gs_models')
    op.drop_index(op.f('ix_bio_gs_models_id'), table_name='bio_gs_models')
    op.drop_table('bio_gs_models')
    # ### end Alembic commands ###
