"""add_science_engine_models

Revision ID: 8ab6bae802c6
Revises: ee15a10584c9
Create Date: 2026-02-15 10:27:19.800619+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ab6bae802c6'
down_revision = 'ee15a10584c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('base_temp', sa.Float(), nullable=True, comment='Base temperature (C)'),
    sa.Column('opt_temp', sa.Float(), nullable=True, comment='Optimal temperature (C)'),
    sa.Column('max_temp', sa.Float(), nullable=True, comment='Maximum temperature (C)'),
    sa.Column('gdd_emergence', sa.Float(), nullable=True, comment='GDD required for emergence'),
    sa.Column('gdd_flowering', sa.Float(), nullable=True, comment='GDD required for flowering'),
    sa.Column('gdd_maturity', sa.Float(), nullable=True, comment='GDD required for physiological maturity'),
    sa.Column('rue', sa.Float(), nullable=True, comment='Radiation Use Efficiency (g/MJ)'),
    sa.Column('harvest_index', sa.Float(), nullable=True, comment='Harvest Index (Yield/Biomass)'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crop_models_id'), 'crop_models', ['id'], unique=False)
    op.create_index(op.f('ix_crop_models_organization_id'), 'crop_models', ['organization_id'], unique=False)
    op.create_table('environmental_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date_calculated', sa.DateTime(), nullable=False),
    sa.Column('gdd_accumulated', sa.Float(), nullable=True, comment='Growing Degree Days (C)'),
    sa.Column('ptu_accumulated', sa.Float(), nullable=True, comment='Photothermal Units (C * hr)'),
    sa.Column('soil_moisture_index', sa.Float(), nullable=True, comment='0-1 scale (1=saturation)'),
    sa.Column('evapotranspiration', sa.Float(), nullable=True, comment='ET0 in mm/day'),
    sa.Column('source_model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_units_id'), 'environmental_units', ['id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('predicted_flowering_date', sa.DateTime(), nullable=True),
    sa.Column('predicted_maturity_date', sa.DateTime(), nullable=True),
    sa.Column('predicted_yield', sa.Float(), nullable=True, comment='Estimated yield (kg/ha)'),
    sa.Column('predicted_biomass', sa.Float(), nullable=True, comment='Total biomass (kg/ha)'),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True, comment='Execution logs or warnings'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['crop_models.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_id'), 'simulation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_organization_id'), 'simulation_runs', ['organization_id'], unique=False)
    op.create_table('soil_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sodium_category', sa.String(), nullable=True),
    sa.Column('texture_class', sa.String(), nullable=True),
    sa.Column('theta_sat', sa.Float(), nullable=False, comment='Saturated water content (cm3/cm3)'),
    sa.Column('theta_res', sa.Float(), nullable=False, comment='Residual water content (cm3/cm3)'),
    sa.Column('alpha', sa.Float(), nullable=False, comment='Inverse of air entry suction (1/cm)'),
    sa.Column('n_param', sa.Float(), nullable=False, comment='Pore size distribution index'),
    sa.Column('ksat', sa.Float(), nullable=True, comment='Saturated hydraulic conductivity (cm/day)'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_profiles_id'), 'soil_profiles', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # op.alter_column('organizations', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('organizations', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.drop_index(op.f('ix_storage_locations_org_code'), table_name='storage_locations')
    # op.alter_column('users', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('users', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('users', 'created_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.create_index(op.f('ix_storage_locations_org_code'), 'storage_locations', ['organization_id', 'code'], unique=True)
    # op.alter_column('organizations', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('organizations', 'created_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_soil_profiles_id'), table_name='soil_profiles')
    op.drop_table('soil_profiles')
    op.drop_index(op.f('ix_simulation_runs_organization_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_environmental_units_id'), table_name='environmental_units')
    op.drop_table('environmental_units')
    op.drop_index(op.f('ix_crop_models_organization_id'), table_name='crop_models')
    op.drop_index(op.f('ix_crop_models_id'), table_name='crop_models')
    op.drop_table('crop_models')
    # ### end Alembic commands ###
