"""
REEVU Domain Corpus — Semantic Domain Detection

Curated example questions per domain for embedding-based domain classification.
Each domain contains 50+ examples covering explicit queries, implicit descriptions,
cross-domain queries, negation, and natural language descriptions.
"""

from __future__ import annotations

DOMAIN_CORPUS: dict[str, list[str]] = {
    "trials": [
        # Explicit queries
        "Show me the trial results for wheat",
        "Which entries performed best in the 2025 season?",
        "List all active experiments at Hyderabad",
        "What are the trial locations for rice?",
        "Show me all field trials from last year",
        "Which experiments are currently running?",
        "Give me the trial summary for maize",
        "What trials were conducted in Kharif 2024?",
        "Show me experimental data for chickpea",
        "List all trials with more than 3 replications",
        "What are the treatment effects in trial T123?",
        "Show me block designs for ongoing experiments",
        "Which trials have completed data collection?",
        "What are the plot layouts for trial XYZ?",
        "Show me nursery trial results",
        "List all multi-location trials",
        "What experiments are planned for next season?",
        "Show me trial metadata for sorghum",
        "Which trials used randomized complete block design?",
        "What are the replication counts across trials?",
        # Implicit queries
        "The performance varied significantly across sites",
        "We need to compare performance across locations",
        "Results from different sites need analysis",
        "The test locations showed different outcomes",
        "We ran multiple tests this season",
        "The field test data is ready",
        "Different locations gave different results",
        "We tested 50 entries this year",
        "Multiple sites were used for testing",
        "The performance varied significantly",
        "We're comparing entries across sites",
        "The data from different locations is ready",
        "We need to evaluate performance",
        "The results need to be compared",
        "The entries showed different responses",
        # Cross-domain and natural language
        "Compare trial performance with weather data",
        "Which experiments had the best yield?",
        "Show me trials with disease resistance screening",
        "What trials included genomic selection?",
        "List experiments with soil analysis",
        "Which trials collected phenotype data?",
        "Show me trials that tested new varieties",
        "What experiments included marker data?",
        "Which trials had pest scouting?",
        "Show me trials with sensor monitoring",
        "What experiments tested drought tolerance?",
        "List trials with quality trait measurements",
        "Which experiments included parent lines?",
        "Show me trials evaluating germplasm",
        "What trials had the most observations?",
    ],
    "breeding": [
        # Explicit queries
        "Show me the germplasm for rice",
        "What is the pedigree of IR64?",
        "List all wheat varieties in the program",
        "Which cultivars are drought tolerant?",
        "Show me crosses made in 2024",
        "What are the parent lines for this hybrid?",
        "List all entries with blast resistance",
        "Show me the breeding program for maize",
        "Which varieties have high protein content?",
        "What germplasm is available for chickpea?",
        "Show me all F2 populations",
        "List varieties released in the last 5 years",
        "What are the trait profiles for these lines?",
        "Show me pedigree information for variety X",
        "Which accessions have early maturity?",
        "List all breeding lines with rust resistance",
        "What crosses were made this season?",
        "Show me germplasm with high yield potential",
        "Which varieties are suitable for rainfed conditions?",
        "What are the selection criteria for this program?",
        # Implicit queries
        "We need better performing lines",
        "The current varieties aren't yielding well",
        "We're looking for stress-tolerant material",
        "The germplasm needs improvement",
        "We want to develop new varieties",
        "The parent selection is critical",
        "We need diverse genetic material",
        "The crosses didn't produce good offspring",
        "We're selecting for multiple traits",
        "The population needs advancement",
        "We're building a new variety",
        "The genetic base is too narrow",
        "We need to introduce new genes",
        "The selection pressure is high",
        "We're pyramiding resistance genes",
        # Cross-domain and natural language
        "Which varieties performed best in trials?",
        "Show me germplasm with marker data",
        "What varieties have good field performance?",
        "List lines with phenotype observations",
        "Which germplasm has genomic profiles?",
        "Show me varieties tested across locations",
        "What lines have seed availability?",
        "Which varieties are commercially released?",
        "Show me germplasm with disease scores",
        "What varieties have quality trait data?",
        "List lines with pedigree and performance",
        "Which germplasm has adaptation data?",
        "Show me varieties with market demand",
        "What lines have been evaluated for yield?",
        "Which varieties have climate resilience?",
    ],
    "phenotyping": [
        # Explicit queries
        "Show me yield observations for wheat",
        "What is the distribution of plant height?",
        "List all phenotype data from trial T123",
        "Show me trait measurements for rice",
        "What are the observation variables collected?",
        "List all scoring data for disease resistance",
        "Show me days to flowering for all entries",
        "What phenotypic data is available for maize?",
        "List all field observations from last season",
        "Show me grain quality measurements",
        "What are the trait values for entry E456?",
        "List all observation units with complete data",
        "Show me phenotype summaries by location",
        "What traits were measured in this trial?",
        "List all observations for plot P789",
        "Show me trait distributions across entries",
        "What are the mean values for each trait?",
        "List all phenotype data with timestamps",
        "Show me observation counts per trait",
        "What is the data completeness for each variable?",
        # Implicit queries
        "My plants are wilting",
        "The leaves are turning yellow",
        "Plants are shorter than expected",
        "The crop is flowering early",
        "Grain filling is poor",
        "The plants look stressed",
        "Leaf color is abnormal",
        "The crop matured too late",
        "Plant vigor is low",
        "The stands are uneven",
        "Lodging is severe in some plots",
        "The ears are small",
        "Tillering is poor",
        "The canopy is sparse",
        "Root development seems weak",
        # Cross-domain and natural language
        "Compare phenotype data across trials",
        "Show me observations with weather context",
        "What traits correlate with yield?",
        "List observations from genomic selection trials",
        "Show me phenotypes for breeding lines",
        "What traits were affected by drought?",
        "List observations with soil data",
        "Show me phenotypes for disease screening",
        "What traits show location effects?",
        "List observations with sensor data",
        "Show me phenotypes for quality traits",
        "What observations indicate stress?",
        "List traits measured in the field",
        "Show me phenotype-genotype associations",
        "What traits distinguish top performers?",
    ],
    "genomics": [
        # Explicit queries
        "Show me SNP markers for chromosome 5",
        "What is the marker density for rice?",
        "List all QTL for yield",
        "Show me genotype data for entry E123",
        "What markers are linked to disease resistance?",
        "List all molecular markers in the database",
        "Show me haplotype information for wheat",
        "What is the allele frequency for marker M456?",
        "List all genomic regions associated with drought tolerance",
        "Show me marker-trait associations",
        "What is the linkage map for maize?",
        "List all genotyping data from 2024",
        "Show me polymorphic markers",
        "What markers are used for selection?",
        "List all QTL mapping results",
        "Show me marker coverage across the genome",
        "What is the genetic distance between markers?",
        "List all markers with significant effects",
        "Show me genotype calls for population P789",
        "What markers differentiate these lines?",
        # Implicit queries
        "We need to identify the genetic basis",
        "The trait is likely controlled by multiple genes",
        "We want to understand the inheritance pattern",
        "The variation needs characterization",
        "We're looking for heritable factors",
        "The molecular analysis is pending",
        "We need confirmation at the molecular level",
        "The diversity is unknown",
        "We want to map the trait",
        "The heritable factors need identification",
        "We're screening with molecular tools",
        "The architecture is complex",
        "We need selection at the molecular level",
        "The profiling is in progress",
        "We're validating the heritable region",
        # Cross-domain and natural language
        "Show me markers for high-yielding lines",
        "What genomic regions affect phenotypes?",
        "List markers used in breeding programs",
        "Show me genotype-phenotype correlations",
        "What markers are in commercial varieties?",
        "List genomic data for trial entries",
        "Show me markers associated with field performance",
        "What genomic regions show selection signatures?",
        "List markers for climate adaptation",
        "Show me genomic predictions for yield",
        "What markers are linked to quality traits?",
        "List genomic data with pedigree information",
        "Show me markers for disease resistance breeding",
        "What genomic regions control stress tolerance?",
        "List markers validated across environments",
    ],
    "weather": [
        # Explicit queries
        "Show me rainfall data for Hyderabad",
        "What was the temperature last month?",
        "List all weather records for 2024",
        "Show me growing degree days for wheat",
        "What is the humidity trend this season?",
        "List all frost events in the last year",
        "Show me precipitation patterns",
        "What was the solar radiation yesterday?",
        "List all weather stations in the region",
        "Show me wind speed data",
        "What is the forecast for next week?",
        "List all drought periods in 2023",
        "Show me daily temperature ranges",
        "What was the rainfall during flowering?",
        "List all weather data for trial locations",
        "Show me climate summaries by month",
        "What is the evapotranspiration rate?",
        "List all extreme weather events",
        "Show me weather patterns during crop season",
        "What was the temperature during grain filling?",
        # Implicit queries
        "It's been very dry lately",
        "The heat is affecting the crop",
        "We had unexpected frost",
        "The rains came late this year",
        "It's been unusually cold",
        "The humidity is very high",
        "We're experiencing drought conditions",
        "The weather has been erratic",
        "It rained during harvest",
        "The temperature dropped suddenly",
        "We had a heatwave last month",
        "The monsoon was delayed",
        "It's been cloudy for weeks",
        "The winds are strong today",
        "We're expecting storms",
        # Cross-domain and natural language
        "How did weather affect trial yields?",
        "Show me weather during the growing season",
        "What weather conditions favor disease?",
        "List weather data for field locations",
        "Show me weather impact on phenotypes",
        "What weather patterns affect breeding decisions?",
        "List weather conditions during stress periods",
        "Show me weather for sensor locations",
        "What weather data correlates with performance?",
        "List weather conditions for planting decisions",
        "Show me weather trends for crop planning",
        "What weather affects soil moisture?",
        "List weather data for spatial analysis",
        "Show me weather during pest outbreaks",
        "What weather conditions optimize yield?",
    ],
    "field": [
        # Explicit queries
        "Show me field locations for wheat trials",
        "What is the planting date for field F123?",
        "List all fields with crop calendar data",
        "Show me field layouts for this season",
        "What is the harvest schedule?",
        "List all field management activities",
        "Show me field history for location L456",
        "What crops were planted last year?",
        "List all fields with rotation data",
        "Show me field preparation activities",
        "What is the sowing window for rice?",
        "List all fields by size",
        "Show me field coordinates",
        "What is the cropping pattern?",
        "List all field operations by date",
        "Show me field allocation for trials",
        "What fields are available for planting?",
        "List all field maintenance records",
        "Show me field boundaries",
        "What is the field capacity?",
        # Implicit queries
        "The field is ready for planting",
        "We need to prepare the land",
        "The plots are marked out",
        "The location is suitable",
        "We're planning the layout",
        "The site has good access",
        "The area needs leveling",
        "We're rotating crops this year",
        "The field was fallow last season",
        "We need to schedule operations",
        "The land preparation is complete",
        "We're allocating space for trials",
        "The site selection is critical",
        "We need to map the area",
        "The field boundaries are clear",
        # Cross-domain and natural language
        "Show me fields with trial data",
        "What fields have weather stations?",
        "List fields with soil analysis",
        "Show me fields for breeding trials",
        "What fields have sensor coverage?",
        "List fields with historical yield data",
        "Show me fields suitable for experiments",
        "What fields have irrigation?",
        "List fields with pest monitoring",
        "Show me fields for phenotyping",
        "What fields are near each other?",
        "List fields with complete records",
        "Show me fields for next season",
        "What fields have good drainage?",
        "List fields by crop suitability",
    ],
    "soil": [
        # Explicit queries
        "Show me soil pH for field F123",
        "What are the nutrient levels?",
        "List all soil analysis records",
        "Show me nitrogen content by location",
        "What is the organic matter percentage?",
        "List all soil test results from 2024",
        "Show me phosphorus levels",
        "What is the soil type at this location?",
        "List all soil health indicators",
        "Show me potassium availability",
        "What are the NPK values?",
        "List all soil fertility data",
        "Show me soil texture analysis",
        "What is the cation exchange capacity?",
        "List all soil moisture measurements",
        "Show me soil profile data",
        "What are the micronutrient levels?",
        "List all soil sampling dates",
        "Show me soil salinity data",
        "What is the soil carbon content?",
        # Implicit queries
        "The land is acidic",
        "Deficiency is visible in the leaves",
        "The quality of the land is poor",
        "The land is degraded",
        "We need to improve fertility",
        "The land is compacted",
        "Drainage is a problem",
        "The texture is sandy",
        "We need to add amendments",
        "The health of the land is declining",
        "The land needs fertilization",
        "The area is waterlogged",
        "We're seeing deficiency stress",
        "The structure is poor",
        "We need to test the land",
        # Cross-domain and natural language
        "How does soil affect yield?",
        "Show me soil data for trial locations",
        "What soil conditions favor this crop?",
        "List soil data with field information",
        "Show me soil-weather interactions",
        "What soil types are in the region?",
        "List soil data for breeding sites",
        "Show me soil fertility trends",
        "What soil factors affect phenotypes?",
        "List soil data with sensor readings",
        "Show me soil conditions for planting",
        "What soil amendments are needed?",
        "List soil data by location",
        "Show me soil-yield relationships",
        "What soil tests are recommended?",
    ],
    "pest_disease": [
        # Explicit queries
        "Show me disease resistance profiles",
        "What varieties are resistant to blast?",
        "List all pest scouting records",
        "Show me disease incidence data",
        "What is the rust severity rating?",
        "List all pathogen screening results",
        "Show me insect damage scores",
        "What diseases were observed in trial T123?",
        "List all pest pressure data",
        "Show me fungal disease records",
        "What is the aphid infestation level?",
        "List all disease resistance genes",
        "Show me bacterial blight scores",
        "What pests are prevalent this season?",
        "List all scouting observations",
        "Show me disease progression over time",
        "What is the wilt incidence?",
        "List all pest management records",
        "Show me nematode damage data",
        "What diseases affect this crop?",
        # Implicit queries
        "My plants have yellow leaves",
        "The leaves are spotted",
        "Plants are dying in patches",
        "The crop looks diseased",
        "Insects are damaging the plants",
        "The leaves are curling",
        "There are holes in the leaves",
        "The plants are stunted",
        "The stems are rotting",
        "We're seeing wilting",
        "The crop is under attack",
        "The leaves have lesions",
        "Plants are showing symptoms",
        "The damage is spreading",
        "We're losing plants",
        # Cross-domain and natural language
        "Show me disease data from trials",
        "What weather favors disease development?",
        "List varieties with resistance",
        "Show me disease impact on yield",
        "What genomic regions confer resistance?",
        "List disease scores with phenotype data",
        "Show me pest pressure by location",
        "What diseases are in the breeding program?",
        "List disease data with field information",
        "Show me disease-weather correlations",
        "What pests affect this germplasm?",
        "List disease resistance in released varieties",
        "Show me pest scouting with sensor data",
        "What diseases reduce quality?",
        "List disease data for spatial analysis",
    ],
    "seed_ops": [
        # Explicit queries
        "Show me seed lot inventory",
        "What is the seed availability for variety V123?",
        "List all seed requests from 2024",
        "Show me seed stock levels",
        "What is the seed quantity for this accession?",
        "List all seedlot records",
        "Show me seed storage locations",
        "What is the seed viability?",
        "List all seed bank accessions",
        "Show me seed supply status",
        "What seed lots are available?",
        "List all germplasm stock",
        "Show me seed request history",
        "What is the seed inventory by variety?",
        "List all seed production records",
        "Show me seed quality data",
        "What seed lots need replenishment?",
        "List all seed distribution records",
        "Show me seed lot purity",
        "What is the seed germination rate?",
        # Implicit queries
        "We need more material",
        "The stock is low",
        "We're running out of material",
        "The quality is questionable",
        "We need to order more",
        "The inventory needs updating",
        "We're short on material",
        "The germination was poor",
        "We need to replenish stock",
        "The material is old",
        "We're tracking usage",
        "The supply is critical",
        "We need to check availability",
        "The storage needs attention",
        "We're managing requests",
        # Cross-domain and natural language
        "Show me seed for breeding lines",
        "What seed is available for trials?",
        "List seed inventory for released varieties",
        "Show me seed for germplasm evaluation",
        "What seed lots have genotype data?",
        "List seed availability by location",
        "Show me seed for next season's trials",
        "What seed is in commercial production?",
        "List seed with pedigree information",
        "Show me seed for phenotyping trials",
        "What seed lots are disease-free?",
        "List seed inventory for breeding program",
        "Show me seed distribution to farmers",
        "What seed is suitable for this environment?",
        "List seed with quality certification",
    ],
    "sensors": [
        # Explicit queries
        "Show me sensor readings from field F123",
        "What is the soil moisture sensor data?",
        "List all IoT device readings",
        "Show me telemetry data for today",
        "What sensors are active?",
        "List all data logger records",
        "Show me environmental sensor data",
        "What is the sensor status?",
        "List all monitoring station data",
        "Show me weather station sensor readings",
        "What sensors are deployed in the field?",
        "List all sensor data from last week",
        "Show me real-time sensor values",
        "What is the sensor battery status?",
        "List all sensor calibration records",
        "Show me sensor data trends",
        "What sensors need maintenance?",
        "List all sensor locations",
        "Show me sensor data quality",
        "What is the sensor sampling frequency?",
        # Implicit queries
        "The monitoring system is active",
        "We're collecting real-time data",
        "The devices are transmitting",
        "We have automated measurements",
        "The data is coming in continuously",
        "We're tracking conditions remotely",
        "The monitoring equipment is installed",
        "We're getting automated readings",
        "The data collection is automated",
        "We have continuous monitoring",
        "The devices are recording data",
        "We're using remote sensing",
        "The monitoring network is operational",
        "We have telemetry from the field",
        "The automated system is working",
        # Cross-domain and natural language
        "Show me sensor data with weather",
        "What sensor readings correlate with yield?",
        "List sensor data for trial locations",
        "Show me sensor data during stress periods",
        "What sensors monitor soil conditions?",
        "List sensor data with field information",
        "Show me sensor readings during crop growth",
        "What sensor data helps decision-making?",
        "List sensor data for irrigation scheduling",
        "Show me sensor data with phenotype observations",
        "What sensors detect environmental stress?",
        "List sensor data for spatial analysis",
        "Show me sensor data for pest monitoring",
        "What sensor readings indicate problems?",
        "List sensor data for crop modeling",
    ],
    "spatial": [
        # Explicit queries
        "Show me locations within 50 km",
        "What trials are nearby?",
        "List all sites in this region",
        "Show me the map of field locations",
        "What is the distance between sites?",
        "List all locations by proximity",
        "Show me spatial distribution of trials",
        "What locations are in the same area?",
        "List all coordinates for fields",
        "Show me the closest weather station",
        "What sites are within this radius?",
        "List all locations on the map",
        "Show me geographic clustering of trials",
        "What is the spatial coverage?",
        "List all sites by region",
        "Show me location-based summaries",
        "What locations are near each other?",
        "List all GIS data",
        "Show me spatial patterns",
        "What is the geographic distribution?",
        # Implicit queries
        "The sites are close together",
        "We need to find nearby locations",
        "The geographic spread is important",
        "We're looking at regional patterns",
        "The locations are clustered",
        "We need to map the sites",
        "The spatial arrangement matters",
        "We're analyzing by area",
        "The locations are distributed",
        "We need to consider distance",
        "The regional context is relevant",
        "We're looking at proximity",
        "The geographic factors are important",
        "We need to visualize locations",
        "The spatial relationships are key",
        # Cross-domain and natural language
        "Show me trials near weather stations",
        "What locations have similar soil types?",
        "List nearby fields with trial data",
        "Show me spatial patterns in yield",
        "What locations are in the same climate zone?",
        "List sites with similar environmental conditions",
        "Show me geographic distribution of varieties",
        "What locations have sensor coverage?",
        "List nearby sites for comparison",
        "Show me spatial variation in phenotypes",
        "What locations are suitable for trials?",
        "List sites by geographic region",
        "Show me spatial clustering of performance",
        "What locations have complete data?",
        "List sites for multi-location analysis",
    ],
    "protocols": [
        # Explicit queries
        "Show me speed breeding protocols",
        "What is the photoperiod for wheat?",
        "List all growth chamber protocols",
        "Show me generation advancement protocols",
        "What protocols are used for rice?",
        "List all breeding protocols",
        "Show me accelerated breeding methods",
        "What is the protocol for trait screening?",
        "List all protocol conditions",
        "Show me generation time data",
        "What protocols achieve 3 generations per year?",
        "List all protocol records",
        "Show me protocol parameters",
        "What is the standard protocol for this crop?",
        "List all protocol variations",
        "Show me protocol optimization data",
        "What protocols are most efficient?",
        "List all protocol documentation",
        "Show me protocol success rates",
        "What protocols are recommended?",
        # Implicit queries
        "We need to speed up the cycle",
        "The generation time is too long",
        "We want to accelerate development",
        "The process needs optimization",
        "We're using controlled conditions",
        "The growth chamber is set up",
        "We need faster turnover",
        "The method needs refinement",
        "We're advancing quickly",
        "The cycle is shortened",
        "We're using rapid cycling",
        "The method is working well",
        "We need to optimize conditions",
        "The advancement is on track",
        "We're following the method",
        # Cross-domain and natural language
        "Show me protocols for breeding programs",
        "What protocols are used in trials?",
        "List protocols with success data",
        "Show me protocols for trait evaluation",
        "What protocols optimize breeding efficiency?",
        "List protocols by crop type",
        "Show me protocols with environmental control",
        "What protocols are used for selection?",
        "List protocols for germplasm development",
        "Show me protocols with generation data",
        "What protocols reduce breeding time?",
        "List protocols for phenotyping",
        "Show me protocols for crossing",
        "What protocols are validated?",
        "List protocols for variety development",
    ],
    "analytics": [
        # Explicit queries
        "Calculate the yield statistics",
        "Show me the performance ranking",
        "What is the correlation between traits?",
        "Analyze the trial data",
        "Predict the yield for next season",
        "Compare the varieties",
        "What is the trend over years?",
        "Run a regression analysis",
        "Show me the stability analysis",
        "Calculate the heritability",
        "What is the yield gap?",
        "Analyze the genotype by environment interaction",
        "Show me the statistical summary",
        "What are the top performers?",
        "Calculate the selection index",
        "Show me the BLUP values",
        "What is the genetic gain?",
        "Analyze the variance components",
        "Show me the performance forecast",
        "Calculate the breeding values",
        # Implicit queries
        "We need to identify the best entries",
        "The data needs statistical analysis",
        "We want to make predictions",
        "The performance needs evaluation",
        "We're comparing results",
        "The trends are important",
        "We need to rank the entries",
        "The analysis is pending",
        "We want to understand patterns",
        "The statistics will guide decisions",
        "We're evaluating performance",
        "The data needs interpretation",
        "We want to forecast outcomes",
        "The comparison is critical",
        "We need quantitative insights",
        # Cross-domain and natural language
        "Analyze trial data with weather",
        "Compare phenotypes across locations",
        "Predict yield using genomic data",
        "Analyze breeding program progress",
        "Compare varieties with soil data",
        "Analyze disease impact on yield",
        "Compare performance across years",
        "Analyze spatial patterns in data",
        "Compare entries with pedigree information",
        "Analyze sensor data trends",
        "Compare field performance",
        "Analyze genotype-phenotype associations",
        "Compare seed lot quality",
        "Analyze protocol efficiency",
        "Compare pest pressure effects",
    ],
}
