"""
Future Module Schemas

Pydantic schemas for planned BijMantra modules (Tier 1-3).
Matches models in app/models/future/.
"""

from app.schemas.future.crop_intelligence import (
    CropCalendar,
    CropCalendarBase,
    CropCalendarCreate,
    CropCalendarUpdate,
    CropSuitability,
    CropSuitabilityBase,
    CropSuitabilityCreate,
    GrowingDegreeDayLog,
    GrowingDegreeDayLogBase,
    GrowingDegreeDayLogCreate,
    GrowingDegreeDayLogUpdate,
    YieldPrediction,
    YieldPredictionBase,
    YieldPredictionCreate,
)
from app.schemas.future.crop_protection import (
    DiseaseRiskForecast,
    DiseaseRiskForecastBase,
    DiseaseRiskForecastCreate,
    IPMStrategy,
    IPMStrategyBase,
    IPMStrategyCreate,
    IPMStrategyUpdate,
    PestObservation,
    PestObservationBase,
    PestObservationCreate,
    SprayApplication,
    SprayApplicationBase,
    SprayApplicationCreate,
    SprayApplicationUpdate,
)
from app.schemas.future.gdd_prediction import (
    GDDPredictionBase,
    GDDPredictionCreate,
    GDDPredictionResponse,
    GDDPredictionUpdate,
)
from app.schemas.future.soil_nutrients import (
    CarbonSequestration,
    CarbonSequestrationBase,
    CarbonSequestrationCreate,
    FertilizerRecommendation,
    FertilizerRecommendationBase,
    FertilizerRecommendationCreate,
    NutrientSufficiency,
    NutrientSufficiencyParams,
    SoilHealthScore,
    SoilHealthScoreBase,
    SoilHealthScoreCreate,
    SoilTest,
    SoilTestBase,
    SoilTestCreate,
    SoilTestUpdate,
)
from app.schemas.future.water_irrigation import (
    Field as FieldSchema,
)
from app.schemas.future.water_irrigation import (
    FieldBase,
    FieldCreate,
    FieldUpdate,
    IrrigationSchedule,
    IrrigationScheduleBase,
    IrrigationScheduleCreate,
    IrrigationScheduleUpdate,
    IrrigationStatus,
    SoilMoistureReading,
    SoilMoistureReadingBase,
    SoilMoistureReadingCreate,
    WaterBalance,
    WaterBalanceBase,
    WaterBalanceCreate,
)


__all__ = [
    # Crop Intelligence
    "GrowingDegreeDayLogBase",
    "GrowingDegreeDayLogCreate",
    "GrowingDegreeDayLogUpdate",
    "GrowingDegreeDayLog",
    "GDDPredictionBase",
    "GDDPredictionCreate",
    "GDDPredictionUpdate",
    "GDDPredictionResponse",
    "CropCalendarBase",
    "CropCalendarCreate",
    "CropCalendarUpdate",
    "CropCalendar",
    "CropSuitabilityBase",
    "CropSuitabilityCreate",
    "CropSuitability",
    "YieldPredictionBase",
    "YieldPredictionCreate",
    "YieldPrediction",
    # Soil & Nutrients
    "SoilTestBase",
    "SoilTestCreate",
    "SoilTestUpdate",
    "SoilTest",
    "SoilHealthScoreBase",
    "SoilHealthScoreCreate",
    "SoilHealthScore",
    "FertilizerRecommendationBase",
    "FertilizerRecommendationCreate",
    "FertilizerRecommendation",
    "CarbonSequestrationBase",
    "CarbonSequestrationCreate",
    "CarbonSequestration",
    "NutrientSufficiencyParams",
    "NutrientSufficiency",
    # Water & Irrigation
    "FieldBase",
    "FieldCreate",
    "FieldUpdate",
    "FieldSchema",
    "WaterBalanceBase",
    "WaterBalanceCreate",
    "WaterBalance",
    "IrrigationScheduleBase",
    "IrrigationScheduleCreate",
    "IrrigationScheduleUpdate",
    "IrrigationSchedule",
    "IrrigationStatus",
    "SoilMoistureReadingBase",
    "SoilMoistureReadingCreate",
    "SoilMoistureReading",
    # Crop Protection
    "DiseaseRiskForecastBase",
    "DiseaseRiskForecastCreate",
    "DiseaseRiskForecast",
    "SprayApplicationBase",
    "SprayApplicationCreate",
    "SprayApplicationUpdate",
    "SprayApplication",
    "PestObservationBase",
    "PestObservationCreate",
    "PestObservation",
    "IPMStrategyBase",
    "IPMStrategyCreate",
    "IPMStrategyUpdate",
    "IPMStrategy",
]
